version: '3'
services:
  postgres:
    image: 'postgres'
    container_name: 'backend-book-blog'
    environment:
      POSTGRES_DB: 'backend-book-blog-db'
      POSTGRES_USER: 'timschauder'
      POSTGRES_PASSWORD: 'password'
      ALLOW_IP_RANGE: '0.0.0.0/0'
    ports:
      - '5432:5432'
  postgresTest:
    image: 'postgres'
    container_name: 'backend-book-blog-test'
    environment:
      POSTGRES_DB: 'templateTest'
      POSTGRES_USER: 'templateTestUser'
      POSTGRES_PASSWORD: 'templateTestPass'
      ALLOW_IP_RANGE: '0.0.0.0/0'
    ports:
      - '5433:5432'
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
